$(function (){
  //.btn__submitをクリックすると処理を開始する
  $(".btn__submit").on("click",function(){
    //以下それぞれの項目名をconsoleに出力する
    console.log("苗字");
    //以下id,classを取得し、そのvalue値をconsoleに出力する
    console.log($("#family__name").val());
    console.log("名前");
    console.log($("#given__name").val());
    console.log("生年月日");
    //それぞれ取得したクラス名を繋げて出力する
    console.log($(".year").val() + "年" + $(".month").val() + "月" + $(".day").val() + "日");
    console.log("性別");
    //name="gender"にチェックが入っていればそのvalue値を出力する
    console.log($('[name="gender"]:checked').val());
    console.log("職業");
    console.log($(".occupation").val());
    console.log("アカウント名");
    console.log($("#account__name").val());
    console.log("メールアドレス");
    console.log($("#email").val());
    console.log("パスワード");
    console.log($("#password").val());
    console.log("確認用パスワード");
    console.log($("#duplication__password").val());
    console.log("住所");
    console.log($("#address").val());
    console.log("電話番号");
    console.log($("#tel").val());
    console.log("購買情報");
    //name="subscription"にチェックが入っていればそのvalue値をconsoleに出力。それを.eachでループさせる
    $('[name="subscription"]:checked').each(function(){
      console.log($(this).val())
    });
  });
});